# Generated by Django 2.0.6 on 2018-06-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_favouritebook_liking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritebook',
            options={'permissions': (('can_view_all_favourites', 'See favourites'), ('can_edit', 'Edit book'), ('can_mark_as_favourite', 'Set book as favourite'))},
        ),
    ]
